package com.spring_boot_dolls_ticket.project.model;

import java.util.Date;

public class PerformanceVO {

	private String PERFORMANCE_ID;
	private String PERFORMANCE_KIND_CD;
	private int PERFORMANCE_RATING_CODE;
	private String PERFORMANCE_NAME;
	private int PERFORMANCE_PRICE;
	private String PERFORMANCE_ZIPCODE;
	private String PERFORMANCE_ADDRESS;
	private String PERFORMANCE_DETAILADDRESS;
	private String PERFORMANCE_DATE;
	private String RESERVATION_OPEN_EXPECTED_DATE;
	private String PERFORMANCE_IMAGE_PATH;
	private Date FIRST_CHANGE_DATE;
	private Date LAST_CHANGE_DATE;
	private int PERFORMANCE_TIME;
	
	public String getPERFORMANCE_ID() {
		return PERFORMANCE_ID;
	}
	public void setPERFORMANCE_ID(String pERFORMANCE_ID) {
		PERFORMANCE_ID = pERFORMANCE_ID;
	}
	public String getPERFORMANCE_KIND_CD() {
		return PERFORMANCE_KIND_CD;
	}
	public void setPERFORMANCE_KIND_CD(String pERFORMANCE_KIND_CD) {
		PERFORMANCE_KIND_CD = pERFORMANCE_KIND_CD;
	}
	public int getPERFORMANCE_RATING_CODE() {
		return PERFORMANCE_RATING_CODE;
	}
	public void setPERFORMANCE_RATING_CODE(int pERFORMANCE_RATING_CODE) {
		PERFORMANCE_RATING_CODE = pERFORMANCE_RATING_CODE;
	}
	public String getPERFORMANCE_NAME() {
		return PERFORMANCE_NAME;
	}
	public void setPERFORMANCE_NAME(String pERFORMANCE_NAME) {
		PERFORMANCE_NAME = pERFORMANCE_NAME;
	}
	public int getPERFORMANCE_PRICE() {
		return PERFORMANCE_PRICE;
	}
	public void setPERFORMANCE_PRICE(int pERFORMANCE_PRICE) {
		PERFORMANCE_PRICE = pERFORMANCE_PRICE;
	}
	public String getPERFORMANCE_ZIPCODE() {
		return PERFORMANCE_ZIPCODE;
	}
	public void setPERFORMANCE_ZIPCODE(String pERFORMANCE_ZIPCODE) {
		PERFORMANCE_ZIPCODE = pERFORMANCE_ZIPCODE;
	}
	public String getPERFORMANCE_ADDRESS() {
		return PERFORMANCE_ADDRESS;
	}
	public void setPERFORMANCE_ADDRESS(String pERFORMANCE_ADDRESS) {
		PERFORMANCE_ADDRESS = pERFORMANCE_ADDRESS;
	}
	public String getPERFORMANCE_DETAILADDRESS() {
		return PERFORMANCE_DETAILADDRESS;
	}
	public void setPERFORMANCE_DETAILADDRESS(String pERFORMANCE_DETAILADDRESS) {
		PERFORMANCE_DETAILADDRESS = pERFORMANCE_DETAILADDRESS;
	}
	public String getPERFORMANCE_DATE() {
		return PERFORMANCE_DATE;
	}
	public void setPERFORMANCE_DATE(String pERFORMANCE_DATE) {
		PERFORMANCE_DATE = pERFORMANCE_DATE;
	}
	public String getRESERVATION_OPEN_EXPECTED_DATE() {
		return RESERVATION_OPEN_EXPECTED_DATE;
	}
	public void setRESERVATION_OPEN_EXPECTED_DATE(String rESERVATION_OPEN_EXPECTED_DATE) {
		RESERVATION_OPEN_EXPECTED_DATE = rESERVATION_OPEN_EXPECTED_DATE;
	}
	public String getPERFORMANCE_IMAGE_PATH() {
		return PERFORMANCE_IMAGE_PATH;
	}
	public void setPERFORMANCE_IMAGE_PATH(String pERFORMANCE_IMAGE_PATH) {
		PERFORMANCE_IMAGE_PATH = pERFORMANCE_IMAGE_PATH;
	}
	public Date getFIRST_CHANGE_DATE() {
		return FIRST_CHANGE_DATE;
	}
	public void setFIRST_CHANGE_DATE(Date fIRST_CHANGE_DATE) {
		FIRST_CHANGE_DATE = fIRST_CHANGE_DATE;
	}
	public Date getLAST_CHANGE_DATE() {
		return LAST_CHANGE_DATE;
	}
	public void setLAST_CHANGE_DATE(Date lAST_CHANGE_DATE) {
		LAST_CHANGE_DATE = lAST_CHANGE_DATE;
	}
	public int getPERFORMANCE_TIME() {
		return PERFORMANCE_TIME;
	}
	public void setPERFORMANCE_TIME(int pERFORMANCE_TIME) {
		PERFORMANCE_TIME = pERFORMANCE_TIME;
	}
	
	
	
}
